version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: dslist_seof_user
      POSTGRES_PASSWORD: pCn2zDDV4CAEp6sF1mYzM77LIkHVXhr4
      POSTGRES_DB: dsfilmes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: projetofilmes
    container_name: spring_app_container
    restart: always
    environment:
      POSTGRES_USER: dslist_seof_user
      POSTGRES_PASSWORD: pCn2zDDV4CAEp6sF1mYzM77LIkHVXhr4
      POSTGRES_DB: dsfilmes
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
