create table tb_filmes (id bigint generated by default as identity, actors varchar(255), plot varchar(255), poster varchar(255), title varchar(255), primary key (id));

INSERT INTO tb_filmes (title, poster, plot, actors)
VALUES
('Sonic', 'https://m.media-amazon.com/images/M/MV5BZGJkOTNmZmQtZjZhYS00NzlmLWE3YzEtMzgzNzgyYWYwY2YzXkEyXkFqcGc@._V1_SX300.jpg', 
 'The evil Dr. Robotnik takes over the planet Mobius, and it is up to Sonic the Hedgehog to put a stop to his evil plans.',
 'Jaleel White, DJ Hazard, Lauren Schacher'),
('Avatar', 'https://m.media-amazon.com/images/M/MV5BMDEzMmQwZjctZWU2My00MWNlLWE0NjItMDJlYTRlNGJiZjcyXkEyXkFqcGc@._V1_SX300.jpg', 
 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
 'Sam Worthington, Zoe Saldana, Sigourney Weaver'),
('Titanic', 'https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_SX300.jpg', 
 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
 'Leonardo DiCaprio, Kate Winslet, Billy Zane'),
('Prison Break', 'https://m.media-amazon.com/images/M/MV5BMTg3NTkwNzAxOF5BMl5BanBnXkFtZTcwMjM1NjI5MQ@@._V1_SX300.jpg', 
 'A structural engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence by breaking themselves out from the inside.',
 'Dominic Purcell, Wentworth Miller, Amaury Nolasco');
